### PR TITLE
circle.radius is now actually a radius

### PR DESCRIPTION
**Pull request by zdenek-biberle**
It used to be a diameter, which made its lowest bit useless.

### CODE REVIEW

**Review by Hnatekmar — APPROVED** [review]
This change should speed up things although change in performance should be minor it makes search space somewhat smaller which is good thing in my book.

**Comment by axeII** [comment]
Please add description.

**Comment by zdenek-biberle** [comment]
@L3rchal Merge this and **** and **** *** a ****ing ******.

**Comment by axeII** [comment]
@fast4shoot Ok... but you still need to add a description.

**Comment by zdenek-biberle** [comment]
\*a description

**Review by axeII — CHANGES_REQUESTED** [review]
Missing description.

**Review by axeII — APPROVED** [review]

**Comment by axeII** [comment]
Merged.

**Pull request merged**
